### ISSUE TITLE
Copilot

### ISSUE THREAD

**Issue by SoyJuanPy** [Gentleman-Programming/Gentleman.Dots#12]
En el apartado de nvim/lua/plugins el de copilot en la linea 83 toma algunas funciones del codigo como comentarios

**Comment by Alan-TheGentleman** [comment]
Buenas! Podrías darme un ejemplo ? Lo veo bien por estos lados

**Comment by SoyJuanPy** [comment]
![muestra 2](https://github.com/user-attachments/assets/67110f5a-1f76-4416-ad2c-52065efdadc2)
![muestra 1](https://github.com/user-attachments/assets/b43bf528-631c-43b1-86e5-57430796de06)
![muestra 3](https://github.com/user-attachments/assets/ab36aadf-e3bc-49d4-a54b-39709f490d27)
Aqui te paso las imagenes

**Comment by Alan-TheGentleman** [comment]
Fixed !! Muchas gracias ☺️

**Comment by Alan-TheGentleman** [comment]
Fixed: ca922e2

**Comment by Alan-TheGentleman** [comment]
Fixed: ca922e2
