### ISSUE TITLE
cargo command unavailable after automatic Rust installation

### ISSUE THREAD

**Issue by tintinando** [Gentleman-Programming/Gentleman.Dots#15]
After an automatic installation of Rust, the cargo command is not immediately available.

The command only works if the environment is explicitly configured by running
`. $HOME/.cargo/env` for bash/zsh or
`source $HOME/.cargo/env.fish` for fish shell.

**Comment by Alan-TheGentleman** [comment]
Fixed with https://github.com/Gentleman-Programming/Gentleman.Dots/issues/15

Could you please check ? :)

**Comment by tintinando** [comment]
It works!
SO: Linux Mint
Terminal: Bash
