### ISSUE TITLE
Error en la instalacion automatica

### ISSUE THREAD

**Issue by ryaguachi** [Gentleman-Programming/Gentleman.Dots#17]
Hola Alan, estaba tratando de correr el sh, pero me da error en una linea como adjunto en la imagen:
![Screenshot from 2024-11-05 17-43-02](https://github.com/user-attachments/assets/c25abf66-e68a-4d92-aa4c-6165266a95a4)

Estoy tratando de ejecutarlo en ubunto 24.

Pd: soy nuevo en esto. te agradezco muhgco si puedes resolverlo. ❤️

**Comment by Alan-TheGentleman** [comment]
Puedes tratar de nuevo ? no me da el error en local :) pero justo he tocado cosas del script

**Comment by ryaguachi** [comment]
No, por si aca le hice un pull, pero estoy al dia y me sige generando el error. 😢

**Comment by Alan-TheGentleman** [comment]
ah pera, no uses sh, directamente ejecuta el script con ./install-linux-mac.sh

**Comment by ryaguachi** [comment]
Jaja si funo, gracias Alan y lo siento las molestias, te quiero, voy aseguir.

**Comment by Alan-TheGentleman** [comment]
Esoooo, cualquier cosita vente al Discord, pd: acabo de subir un fix para zsh ;)
