### ISSUE TITLE
Bug on arch wsl

### ISSUE THREAD

**Issue by usarral** [Gentleman-Programming/Gentleman.Dots#18]
Hi,

When I try to run the autoinstall on WSL Arch, I encounter a bug on line 116:

```shell
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'
stable-x86_64-unknown-linux-gnu installed - rustc 1.82.0 (f6e511eec 2024-10-15)
./install-linux-mac.sh: line 116: /home/usarral/.cargo/env: No such file or directory
```
Is this an issue on my end, or is it something beyond my control? I’ve reinstalled it, but the problem persists.

**Comment by Alan-TheGentleman** [comment]
Test now, uploaded a fix :)

**Comment by usarral** [comment]
Now it's a directory: 
./install-linux-mac.sh: line 116: .: /home/usarral/.cargo/env: is a directory


I have discover that using the other linux option (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh) it seems that works becouse it generates .cargo/env, the aur package seems that not. If that helps you

**Comment by Alan-TheGentleman** [comment]
added the same command as linux, tell me if it works !!!

**Comment by usarral** [comment]
Perfect, now it's working, thank you Alan :)
