### ISSUE TITLE
Harpoon Issues

### ISSUE THREAD

**Issue by kevyyar** [Gentleman-Programming/Gentleman.Dots#3]
Al instalar el build, hay problemas para poder usar. Marcar error de harpoon.

![image](https://github.com/Gentleman-Programming/Gentleman.Dots/assets/42918676/aa14b862-1959-4066-ae7a-f1f75e0916dc)

Borre el archivo de harpoo.lua que esta dentro de lua/plugins y parece que se arregla brevemente. Pero la ventana no desaparece que dice #Plugin Updates. 

![image](https://github.com/Gentleman-Programming/Gentleman.Dots/assets/42918676/8df5440c-4461-44db-bd97-e1a014b0587d)

Al volver agregarlo el plugin, creando de nuevo el archivo harpoon.lua, el problema persiste

Sistema: PopOS

**Comment by miguel-hp-dev** [comment]
![image](https://github.com/Gentleman-Programming/Gentleman.Dots/assets/139126430/3891b143-c6c8-4d5a-97f9-5003b4540698)
no logro instala homebrew

**Comment by mi4uel** [comment]
![image](https://github.com/Gentleman-Programming/Gentleman.Dots/assets/71575936/718bd4a1-aacb-4cd8-b42b-fa2b9858b551)
No logro instalar homebrew

**Comment by AppleLAN** [comment]
> ![image](https://private-user-images.githubusercontent.com/71575936/323982170-718bd4a1-aacb-4cd8-b42b-fa2b9858b551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDgyMzksIm5iZiI6MTcxMzU0NzkzOSwicGF0aCI6Ii83MTU3NTkzNi8zMjM5ODIxNzAtNzE4YmQ0YTEtYWFjYi00Y2Q4LWI0MmItZmEyYjk4NThiNTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE3MzIxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmMzE4ZDA4YmQ4ZWNhMTllYzkwYmYwYTZmNmFlNjM5ZjhkYjlkNTFlMDlhZjFlNzYzNjA5NTRiOWIwNDlmOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6_fzroXfFjnlRd6qdxiCtYL9yXmzMi_4m3sCWdHs_eA) No logro instalar homebrew

Hola ! trata de usar el comando que viene por defecto en brew a ver si te funciona:

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

https://brew.sh/

**Comment by AppleLAN** [comment]
> ventana

Ya puse pasos para arreglarlo, parece que hay problema si inicias la config con harpoon.lua puesto, tienes que borrar la config, reiniciar NViM y que haga sus cositas y una vez termine, volver a agregar harpoon.lua.

también puedes usar LazyExtras para instalarlo ya que viene por default como opción
