### ISSUE TITLE
how to select the code hint

### ISSUE THREAD

**Issue by Mrthnx** [Gentleman-Programming/Gentleman.Dots#4]
Hola, acabo de instalar el repo, no tengo ni copilot ni codeium activado, pero cuando escribo codigo en este caso tailwind me sale esta sugerencia, podran ayudarme a saber como seleccionarla, quiero seleccionar todo ese texto que sale como ayuda.

![Screenshot_20240526_175135](https://github.com/Gentleman-Programming/Gentleman.Dots/assets/15071479/82a1dad5-d12d-467e-a0e9-ae320f6134e8)

**Comment by AppleLAN** [comment]
Se llama supermaven ! Aquí tienes los keymaps:

https://github.com/Gentleman-Programming/Gentleman.Dots/blob/main/GentlemanNvim/nvim/lua/plugins/supermaven.lua

**Comment by Mrthnx** [comment]
Mil Gracias :D
