### ISSUE TITLE
feature: make a number select menu for operating system

### ISSUE THREAD

**Issue by drizlye0** [Gentleman-Programming/Gentleman.Dots#7]
Hola, acabo de ver el script de instalacion y el modo de seleccionar la plataforma podria ser un menu selectivo con numeros.

El menu podria ser con un select tal que asi
```
#!/bin/bash

echo "Which operating system are you using?"

select os_choice in Linux Mac None
do
  case $os_choice in
    Linux|Mac)
      break
      ;;
    None)
      echo "No has seleccionado ningún sistema operativo"
      break
      ;;
    *)
      echo "Opción inválida. Por favor, selecciona un número válido."
      ;;
  esac
done

echo "$os_choice"
```
![Screenshot from 2024-08-19 16-00-28](https://github.com/user-attachments/assets/c4156a59-0a87-44c7-b502-efe2ca28cffb)

**Comment by Alan-TheGentleman** [comment]
On it !!

**Comment by Alan-TheGentleman** [comment]
DONE!!! muchas gracias por la idea !! espero que te guste más la configuración :)
